# Generated by Django 4.0.3 on 2023-04-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_jobapply_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('add_file', models.FileField(upload_to='')),
            ],
        ),
    ]
