# Generated by Django 4.0.3 on 2023-10-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_contact_employeedetails_employeelogin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeelogin',
            name='name',
            field=models.CharField(default='', max_length=2322),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='created_at',
            field=models.CharField(default='2023-10-20', max_length=150),
        ),
        migrations.AlterField(
            model_name='jobsrequired',
            name='created_at',
            field=models.CharField(default='2023-10-20', max_length=150),
        ),
        migrations.AlterField(
            model_name='telemetrydaa',
            name='date',
            field=models.CharField(default='2023-10-20', max_length=10),
        ),
    ]
