# Generated by Django 4.0.3 on 2023-10-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_userlogintime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogintime',
            name='jj',
            field=models.CharField(default='null', max_length=88),
        ),
    ]
