# Generated by Django 4.0.3 on 2023-10-20 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_userlogintime_jj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogintime',
            name='jj',
        ),
        migrations.AlterField(
            model_name='userlogintime',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
