# Generated by Django 4.0.3 on 2023-10-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_remove_userlogintime_jj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogintime',
            name='previous_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
