# Generated by Django 4.0.3 on 2023-10-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_userlogintime_previous_login_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='document_base64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='created_at',
            field=models.CharField(default='2023-10-26', max_length=150),
        ),
        migrations.AlterField(
            model_name='jobsrequired',
            name='created_at',
            field=models.CharField(default='2023-10-26', max_length=150),
        ),
        migrations.AlterField(
            model_name='telemetrydaa',
            name='date',
            field=models.CharField(default='2023-10-26', max_length=10),
        ),
    ]
