# Generated by Django 4.0.3 on 2023-10-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_contact_document_base64'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='document_base64',
            new_name='resume_base64',
        ),
    ]
