# Generated by Django 4.0.3 on 2023-10-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_rename_document_base64_contact_resume_base64'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_images/')),
                ('userid', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='ads_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='jobtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
