# Generated by Django 4.0.3 on 2023-10-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_loginprofile_contact_ads_id_contact_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginprofile',
            name='image_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
