# Generated by Django 5.0 on 2023-12-29 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_alter_jobapply_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtoken',
            name='expiration_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1)),
        ),
    ]
