# Generated by Django 5.0 on 2023-12-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_customtoken_expiration_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtoken',
            name='expiration_time',
        ),
    ]
