# Generated by Django 5.0 on 2023-12-29 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0043_remove_customtoken_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtoken',
            name='expiration_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1)),
        ),
    ]
