# Generated by Django 5.0 on 2024-01-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_user_active_devices_user_token_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token_created_at',
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='created_at',
            field=models.CharField(default='2024-01-04', max_length=150),
        ),
        migrations.AlterField(
            model_name='jobsrequired',
            name='created_at',
            field=models.CharField(default='2024-01-04', max_length=150),
        ),
        migrations.AlterField(
            model_name='telemetrydaa',
            name='date',
            field=models.CharField(default='2024-01-04', max_length=10),
        ),
    ]
