# Generated by Django 4.0.3 on 2023-04-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0050_alter_adsmangeme_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspricing',
            name='NoAds',
            field=models.CharField(max_length=2322, null=True),
        ),
    ]
