# Generated by Django 4.0.3 on 2023-09-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0054_businesspricing_chatsupport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_created',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='DaysLimit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_expire',
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='validity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='adsmangeme',
            name='date_created',
            field=models.CharField(default='2023-09-25', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentdetailsvalues',
            name='date',
            field=models.CharField(default='2023-09-25', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='ads_timing',
            field=models.CharField(default='2023-09-25', max_length=30),
        ),
        migrations.AlterField(
            model_name='realestateenquery',
            name='date_created',
            field=models.CharField(default='2023-09-25', max_length=150),
        ),
        migrations.AlterField(
            model_name='reportads',
            name='dates',
            field=models.CharField(default='2023-09-25', max_length=30),
        ),
    ]
