# Generated by Django 4.0.3 on 2023-11-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0059_alter_adsmangeme_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLogin2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('login_time', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude1', models.CharField(blank=True, max_length=255, null=True)),
                ('lattiude1', models.CharField(blank=True, max_length=255, null=True)),
                ('logout_time', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude2', models.CharField(blank=True, max_length=255, null=True)),
                ('lattiude2', models.CharField(blank=True, max_length=255, null=True)),
                ('total_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='adsmangeme',
            name='date_created',
            field=models.CharField(default='2023-11-08', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentdetailsvalues',
            name='date',
            field=models.CharField(default='2023-11-08', max_length=10),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='ads_timing',
            field=models.CharField(default='2023-11-08', max_length=30),
        ),
        migrations.AlterField(
            model_name='realestateenquery',
            name='date_created',
            field=models.CharField(default='2023-11-08', max_length=150),
        ),
        migrations.AlterField(
            model_name='reportads',
            name='dates',
            field=models.CharField(default='2023-11-08', max_length=30),
        ),
    ]
