# Generated by Django 4.0.3 on 2023-11-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0060_employeelogin2_alter_adsmangeme_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tl_name', models.CharField(blank=True, max_length=255, null=True)),
                ('task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.CharField(blank=True, max_length=255, null=True)),
                ('overdue_duedate', models.BooleanField(default=False)),
                ('task_done', models.BooleanField(default=False)),
                ('push_code', models.BooleanField(default=False)),
                ('dev_review', models.BooleanField(default=False)),
            ],
        ),
    ]
