# Generated by Django 5.0 on 2024-01-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0070_rename_content_notification_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
