# Generated by Django 5.0 on 2024-01-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0074_userrecentads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecentads',
            name='ads_id',
            field=models.CharField(max_length=255),
        ),
    ]
