# Generated by Django 4.0.3 on 2023-04-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapi', '0012_alter_order_order_datetele_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('real_estate', 'Real Estate'), ('furniture', 'Furniture'), ('pets', 'Pets'), ('bikes', 'Bikes'), ('cars', 'Cars'), ('electronics', 'Electronics'), ('mobiles', 'Mobiles'), ('services', 'Services')], max_length=20)),
                ('subject', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_dateTele',
            field=models.CharField(default='2023-04-20', max_length=155),
        ),
        migrations.AlterField(
            model_name='transactiondetails',
            name='ordrDate',
            field=models.CharField(default='2023-04-20', max_length=155),
        ),
        migrations.AlterField(
            model_name='transationidone',
            name='date_created',
            field=models.CharField(default='2023-04-20', max_length=550),
        ),
    ]
