# Generated by Django 4.0.3 on 2023-04-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapi', '0014_alter_order_order_datetele_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetails',
            name='adsValue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactiondetails',
            name='monthsVale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
