# Generated by Django 4.0.3 on 2023-04-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapi', '0015_transactiondetails_adsvalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondetails',
            name='City',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
