# Generated by Django 4.0.3 on 2023-04-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapi', '0017_alter_order_order_datetele_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedcustomermain',
            name='OrderID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='verifiedcustomermain',
            name='validity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
